### PR TITLE
Add slides for bonus content and update assignment 2

### PR DESCRIPTION
**Pull request by kaylielau**
Add slides for bonus content (pandas and visualization)
Update Assignment 2 instructions so students can use readline() or readlines() methods

### CODE REVIEW

**Comment by curtissfnorman** [comment]
From my perspective, I see this as feedback from our Technical Facilitator that there is room within the existing module to fit in this content. I am not opposed to this change. The question is, do we incorporate the content into the core slides of this module or into the cohort_three folder as a decision/choice made for this cohort's delivery? Additionally, does this content belong in later modules (visualization, deep learning). @RohanAlexander I defer to you to approve and merge as this is a curriculum decision.

**Comment by kaylielau** [comment]
@curtissfnorman @RohanAlexander there is no room to cover slides relating to APIs, pandas, or visualization. I just wanted to include these in the GitHub repo as a number of students were asking for resources they could refer to in order to learn about these topics. I can create a separate directory with these slides to avoid confusion about what is "core content" and what is "bonus content".

**Comment by curtissfnorman** [comment]
@kaylielau Thank you for clarifying. In light of that, I suggest this content goes into the 06_cohort_three folder. This was the intent behind creating this folder - for material an individual facilitator wishes to share with the cohort during their delivery. Does that work?

**Comment by kaylielau** [comment]
@curtissfnorman thanks for clarifying- I totally agree with this! The slides have been moved :)

**Review by danielrazavi — APPROVED** [review]

**Pull request merged**
